# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2021-10-20 19:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('base_price', models.IntegerField()),
                ('description', models.CharField(max_length=128)),
                ('weight', models.FloatField()),
                ('category', models.CharField(max_length=32)),
            ],
        ),
    ]
